---
title: "Data Carpentry Workshop at Yosemite Field Station (UC Merced)"
subtitle: "Workshop Overview: Open and Reproducible Ecology" 
date: "August 17, 2017"
output: 
  html_document
---



**Instructors and helpers**

- Karen Cranston (twitter: @kcranstn | github: @kcranston)
- Julie Lowndes (twitter: @juliesquid | github: @jules32)
- Jamie Afflerbach (twitter | github: @jafflerbach)
- Noelle Anderson 
- Emily Jane McTavish (twitter | github: @snacktavish)
- Jessica Blois (twitter: @jessicablois)
 
----

> Data scientists, according to interviews and expert estimates, spend from 50 percent to 80 percent of their time mired in the mundane labor of collecting and preparing data, before it can be explored for useful information. - [NYTimes (2014)](http://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html)

# What to expect

This is going to be a fun workshop. The plan is to expose you to a lot of great tools that you can gain confidence using for your research. We're going to go through a lot in these two days and you don't have to remember it all — the main thing to take away is that there *are* good ways to approach your analyses — and you should have confidence in yourself that you can do find them and use them! Googling is a big part of programming. 

We'll be talking about : 

- how to THINK about data. And not just any data; tidy data.
- how to increase reproducibility in your science
- how to more easily collaborate with others — most importantly with your future self!
- how the #rstats community is fantastic. The tools we're using are developed by real people. They are building great stuff and helping people of all skill-levels learn how to use it. 

# Workshop materials 

- [Course Website](https://snacktavish.github.io/2017-08-17-Yosemite/)
- [Workshop Overview](https://snacktavish.github.io/2017-08-17-Yosemite/overview/) (Karen (?))
- [Data organization in spreadsheets and OpenRefine for data cleaning](http://www.datacarpentry.org/OpenRefine-ecology-lesson/) (Karen)
- [Get excited about R and RStudio!](https://snacktavish.github.io/2017-08-17-Yosemite/R-RStudio/) (Julie)
- [Intro to R and RStudio](http://www.datacarpentry.org/R-ecology-lesson/01-intro-to-r.html) (Julie) 
- [Data analysis with dplyr and tidyr](http://www.datacarpentry.org/R-ecology-lesson/03-dplyr.html) (Jamie) 
- [Visualization with ggplot2](http://www.datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html) (Jamie) 
- [Version Control with Git, GitHub, and RStudio](https://snacktavish.github.io/2017-08-17-Yosemite/version-control) (Julie)


## By the end of the course...

